language: python
python:
  - 2.7
  - 3.3
services:
  - docker
  - redis-server
install:
  - 'docker build app .'
  - 'docker run -d -p 127.0.0.1:8080 --name app app'
before_script:
  - 'pip install -r requirements.txt'
  - 'pip install mock'
  - 'pip install requests'
  - 'pip install feedparser'
script:
  - 'docker ps | grep app'
  - 'python tests.py'